name: Bionomia-API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: 3.3.6
      BUNDLER_VERSION: 2.4.6
      RACK_ENV: test

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    - name: Setup Config
      run: |
          cp config/settings/test.yml.sample config/settings/test.yml
    - name: Run tests
      run: RACK_ENV=test bundle exec rake
